[2025-04-01T04:37:23.717+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covertype_workflow.preprocess_data manual__2025-04-01T04:37:02.590660+00:00 [queued]>
[2025-04-01T04:37:23.737+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covertype_workflow.preprocess_data manual__2025-04-01T04:37:02.590660+00:00 [queued]>
[2025-04-01T04:37:23.737+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-04-01T04:37:23.761+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2025-04-01 04:37:02.590660+00:00
[2025-04-01T04:37:23.787+0000] {standard_task_runner.py:57} INFO - Started process 545 to run task
[2025-04-01T04:37:23.803+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'covertype_workflow', 'preprocess_data', 'manual__2025-04-01T04:37:02.590660+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/covertype_workflow.py', '--cfg-path', '/tmp/tmp0_w4zae6']
[2025-04-01T04:37:23.810+0000] {standard_task_runner.py:85} INFO - Job 107: Subtask preprocess_data
[2025-04-01T04:37:23.944+0000] {task_command.py:410} INFO - Running <TaskInstance: covertype_workflow.preprocess_data manual__2025-04-01T04:37:02.590660+00:00 [running]> on host fa1ab66db115
[2025-04-01T04:37:24.148+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covertype_workflow' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T04:37:02.590660+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-01T04:37:02.590660+00:00'
[2025-04-01T04:37:24.204+0000] {covertype_workflow.py:111} INFO - `covertype_raw` está VACÍA. Creando `covertype_preprocessed` vacía...
[2025-04-01T04:37:24.268+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-04-01T04:37:24.312+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=covertype_workflow, task_id=preprocess_data, execution_date=20250401T043702, start_date=20250401T043723, end_date=20250401T043724
[2025-04-01T04:37:24.414+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-04-01T04:37:24.489+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
